version: 0.0
os: linux
files:
  - source: /
    destination : /home/ubuntu/team5/
  #복사할 파일 지정(src -> 대상경로)
# 디렉토니나 파일의 권한 설정
permissions:
  - object : /home/ubuntu/team5/
    pattern: "**"
    owner : root
    group : root
    mode : 750
    type:
      - file
# codeDeploy agentrk 배포 수행시 수행할 이벤트 hook 설정
hooks:
  ApplicationStart:
    - location : scripts/start_server.sh
      timeout : 300
      runas: root
  ApplicationStop:
    - location : scripts/stop_server.sh
      timeout: 300
      runas: root
#  BeforeInstall:
#    - location: scripts/remove_before.sh